[package]
name = "websockets"
version = "0.1.0"
authors = ["bakape <bakape@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.69"
rayon = "1.3.0"
protocol = { path = "../../protocol" }
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.52"
heapless = "0.5.4"
backtrace = "0.3.46"
uuid = "0.8.1"
openssl = { version = "0.10.29", features = ["vendored"] }
syntect = "4.1.1"
htmlescape = "0.3.1"
url = "2.1.1"
regex = "1.3.7"
lazy_static = "1.4.0"
